services:
  db:
    image: mysql
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Battle19.
      MYSQL_DATABASE: language_learning_tracker
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"

volumes:
  mysql-data:
